properties:
  slims:
    type: object

    dependentRequired:
      username: [password, url, find_criteria]
      password: [username, url, find_criteria]
      url: [username, password, find_criteria]

    properties:
      url:
        description: SLIMS URL
        type: string
        format: uri

      username:
        description: SLIMS username
        type: string

      password:
        description: SLIMS password
        type: string
        secret: true

      map:
        description: "Mapping of keys to SLIMS field(s) (Use json: prefix and dot notation for JSON fields)"
        type: mapping
        default: {}

      sync:
        description: "Fields in slims.map that will be synced to SLIMS in a pre and post hook"
        type: array
        items:
          type: string
        default: []

      match:
        description: "Use fields from 'slims.map' when matching samples to augment with SLIMS metadata (in addition to 'sample.id')"
        type: array
        items:
          type: string
        default: []

      derive:
        type: mapping
        description: "Mapping for creating derived records in SLIMS. Top level key identies the derived record. Use curly braces to acces keys in the 'sample' object, eg. '{sample.id}'"
        default: {}

      novel:
        type: object
        properties:
          max_age:
            description: "Maximum age of novel records to consider for matchin (eg. '4 days', '1 year')"
            type: string
            default: 1 year
          criteria:
            description: "SLIMS criteria to use for matching novel records (In conjunction with 'slims.criteria')"
            type: string

      criteria:
        description: SLIMS criteria for finding records (eg. "cntn_cstm_SecondaryAnalysis equals 1337")
        type: string

      dry_run:
        description: Do not sync data to SLIMS
        default: false
        type: boolean

      page_size:
        description: Page size to use when fetching records from SLIMS
        default: 100
        type: integer
