type: object
properties:
  rsync:
    type: object
    properties:
      skip:
        type: boolean
        default: false
        description: "Don't rsync results"
      sge_queue:
        type: string
        description: SGE queue for rsync
      sge_pe:
        type: string
        description: SGE parallel environment for rsync
      sge_slots:
        type: integer
        description: SGE slots (threads) for rsync
        default: 1
      base:
        type: path
        description: Base of directory where results will be stored
      overwrite:
        type: boolean
        description: Overwrite existing results
        default: false
      large_file_threshold:
        type: string
        description: Files larger than this will be copied in a separate job (eg. 100M, 1 GB)
        default: "100M"
    required:
      - sge_queue
      - sge_pe
