name: Sync pyproject.toml

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      module:
        description: The name of the module
        type: string
        required: true
      path:
        description: The working directory (must contain pyproject.toml)
        type: string
        required: true
      version:
        description: The version to pass to set in pyproject.toml
        type: string
        default: ""
      head:
        description: The branch or tag to checkout
        type: string
        required: true

env:
  INPUT_PATH: ${{ inputs.path }}
  INPUT_VERSION: ${{ inputs.version }}
  INPUT_MODULE: ${{ inputs.module }}

jobs:
  sync-pyproject:
    name: Sync pyproject.toml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.head }}
          persist-credentials: false
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: uv-version

        run: uvx --from=toml-cli toml set --toml-path=${INPUT_PATH}/pyproject.toml project.version ${INPUT_VERSION}
      - name: uv-lock
        run: |
          uv export --package cellophane-${INPUT_MODULE} --no-dev --no-hashes > ${INPUT_PATH}/requirements.lock
          uv export --package cellophane-${INPUT_MODULE} --no-hashes > ${INPUT_PATH}/requirements-dev.lock
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ inputs.module }}-meta
          path: |
            ${{ inputs.path }}/pyproject.toml
            ${{ inputs.path }}/requirements.lock
            ${{ inputs.path }}/requirements-dev.lock
          retention-days: 1
