---
name: Generate Changelog

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      head:
        description: The HEAD to get changes from
        required: true
        type: string
      path:
        description: The path to include in the changelog
        required: true
        type: string
    outputs:
      changes:
        description: "Unreleased changes"
        value: "${{ jobs.changelog.outputs.changes }}"

jobs:
  changelog:
    runs-on: ubuntu-latest
    outputs:
      changes: "${{ steps.changelog.outputs.content }}"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.head }}
          fetch-depth: 0
      - name: fix-glob
        id: fix-glob
        run: |
          glob="$(sed 's,//,/,' <<< '${{ inputs.path }}/*')"
          code=$?; [[ "$code" != "0" ]] && exit $code
          echo glob=$glob | tee -a "$GITHUB_OUTPUT"
      - uses: orhun/git-cliff-action@v3
        id: changelog
        with:
          config: cliff.toml
          args: --unreleased --include-path "${{ steps.fix-glob.outputs.glob }}"
