name: Module PR

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      module:
        description: 'Module name'
        type: string
        required: true
      path:
        description: 'Path to the module'
        type: string
        required: true
      has-changes:
        description: 'Wether or not the module has changed'
        type: boolean
        required: true
      head:
        description: 'HEAD to fetch commits from'
        type: string
      base:
        description: 'Base branch to create the PR against'
        type: string
        required: true
      cellophane-repo:
        description: 'Cellophane repo to fetch releases from'
        type: string
        required: true
      cellophane-releases:
        description: 'Cellophane releases to test against'
        type: string
        required: true
    outputs:
      pr-number:
        value: ${{ jobs.module-pr.outputs.pr-number }}
      pr-head-sha:
        value: ${{ jobs.module-pr.outputs.pr-head-sha }}

env:
  INPUTS_MODULE: ${{ inputs.module }}
  INPUTS_HEAD: ${{ inputs.head }}
  INPUTS_BASE: ${{ inputs.base }}

jobs:
  detect-release-branch:
    name: Detect release branch
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.branch-exists.outputs.exists }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Check release branch
        id: branch-exists
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/release/${INPUTS_MODULE}; then
            echo "Branch exists"
            echo "exists=true" | tee "$GITHUB_OUTPUT"
          else
            echo "Branch does not exist"
            echo "exists=false" | tee "$GITHUB_OUTPUT"
          fi

  rebase-module-pr:
    name: Rebase PR
    needs: [detect-release-branch]
    if: (!inputs.has-changes) && (needs.detect-release-branch.outputs.exists == 'true')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: release/${{ inputs.module }}
        fetch-depth: 0
        persist-credentials: true
    - name: Rebase
      run: |
        git config --global user.email "<>"
        git config --global user.name "github-actions[bot]"
        git rebase --onto origin/${INPUTS_BASE} HEAD~2
        git push --force-with-lease

  semver:
    name: Calculate next version
    uses: ./.github/workflows/def_module-semver.yml
    needs: [detect-release-branch]
    if: inputs.has-changes || (needs.detect-release-branch.outputs.exists == 'false')
    with:
      module: ${{ inputs.module }}
      path: ${{ inputs.path }}

  changelog:
    name: Generate changelog
    uses: ./.github/workflows/def_changelog.yml
    needs: [detect-release-branch]
    if: inputs.has-changes || (needs.detect-release-branch.outputs.exists == 'false')
    with:
      head: ${{ inputs.head }}
      path: ${{ inputs.path }}
      module: ${{ inputs.module }}

  sync-pyproject:
    name: Sync pyproject.toml
    uses: ./.github/workflows/def_sync-pyproject.yml
    needs: [detect-release-branch, semver]
    if: inputs.has-changes || (needs.detect-release-branch.outputs.exists == 'false')
    with:
      module: ${{ inputs.module }}
      head: ${{ inputs.head }}
      path: ${{ inputs.path }}
      version: ${{ needs.semver.outputs.next-version }}

  module-pr:
    name: Create or update PR
    needs: [detect-release-branch, semver, sync-pyproject, changelog]
    if: (inputs.has-changes || (needs.detect-release-branch.outputs.exists == 'false'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      pr-number: ${{ steps.create-or-update-pr.outputs.pull-request-number }}
      pr-head-sha: ${{ steps.create-or-update-pr.outputs.pull-request-head-sha }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: ${{ inputs.head }}
        persist-credentials: false
    - name: git-reset
      run: git reset --hard ${INPUTS_HEAD}
    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        pattern: '${{ inputs.module }}-meta'
        path: ${{ inputs.path }}
        merge-multiple: true
    - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      id: create-or-update-pr
      with:
        title: "Release ${{ inputs.module }} ${{ needs.semver.outputs.next-version }} 🚀"
        commit-message: "chore: Bump ${{ inputs.module }} version to ${{ needs.semver.outputs.next-version }}"
        body: ${{ needs.changelog.outputs.changes }}
        branch: release/${{ inputs.module }}
        base: ${{ inputs.base }}
        labels: release

    - uses: actions-ecosystem/action-create-comment@5b43c092bf96ebc715dbbe5682ecf3b771223855 # v1.0.0
      if: steps.create-or-update-pr.outputs.pull-request-operation == 'created'
      with:
        github_token: ${{ github.token }}
        number: ${{ steps.create-or-update-pr.outputs.pull-request-number }}
        body: |
          # 🤖 \*bleep bloop\*

          This is a fully automated module PR. I will be automatically updated with any changes pushed to ${{ inputs.base }}.

          When merged I will ~~achieve world domination~~ tag ${{ needs.semver.outputs.next-tag }}.


  pytest-released:
    name: Run pytest (cellophane releases)
    needs: [detect-release-branch, semver, module-pr]
    if: inputs.has-changes || (needs.detect-release-branch.outputs.exists == 'false')
    uses: ./.github/workflows/def_pytest.yml
    permissions:
      checks: write
      pull-requests: write
    strategy:
      matrix:
        cellophane: ${{ fromJson(inputs.cellophane-releases) }}
      fail-fast: false
    with:
      pr-head-sha: ${{ needs.module-pr.outputs.pr-head-sha }}
      module: ${{ inputs.module }}
      path: ${{ inputs.path }}
      version: ${{ needs.semver.outputs.next-version }}
      cellophane-repo: ${{ inputs.cellophane-repo }}
      cellophane-tag: ${{ matrix.cellophane }}
      generate-support-json: true

  pytest-dev:
    name: Run pytest (cellophane@dev)
    needs: [detect-release-branch, semver, module-pr]
    if: inputs.has-changes || (needs.detect-release-branch.outputs.exists == 'false')
    uses: ./.github/workflows/def_pytest.yml
    permissions:
      checks: write
      pull-requests: write
    with:
      pr-head-sha: ${{ needs.module-pr.outputs.pr-head-sha }}
      module: ${{ inputs.module }}
      path: ${{ inputs.path }}
      version: ${{ needs.semver.outputs.next-version }}
      cellophane-repo: ${{ inputs.cellophane-repo }}
      cellophane-tag: dev
      ignore-fail: true
      publish-results: true
      generate-support-json: true
      check-fail: true

  pytest-latest:
    name: Run pytest (cellophane@latest)
    needs: [detect-release-branch, semver, module-pr]
    if: inputs.has-changes || (needs.detect-release-branch.outputs.exists == 'false')
    uses: ./.github/workflows/def_pytest.yml
    permissions:
      checks: write
      pull-requests: write
    with:
      pr-head-sha: ${{ needs.module-pr.outputs.pr-head-sha }}
      module: ${{ inputs.module }}
      path: ${{ inputs.path }}
      version: ${{ needs.semver.outputs.next-version }}
      cellophane-repo: ${{ inputs.cellophane-repo }}
      cellophane-tag: latest
      publish-results: true
      check-fail: true

  update-module-json:
    name: Update modules.json
    needs: [detect-release-branch, pytest-dev, module-pr, semver]
    if: inputs.has-changes || (needs.detect-release-branch.outputs.exists == 'false')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NEXT_VERSION: ${{ needs.semver.outputs.next-version }}
      NEXT_TAG: ${{ needs.semver.outputs.next-tag }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: release/${{ inputs.module }}
          persist-credentials: false
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: '${{ inputs.module }}-*.support.json'
          merge-multiple: true
      - name: merge-json
        env:
          JQ_SCRIPT: |
            (. | flatten) as $cellophane
            | $modules
            | .[$module].versions[$version] = {cellophane: $cellophane, tag: $tag}
            | .[$module].latest = $version
        run: |
          _modules=$(
            jq \
              --slurp \
              --arg module "${INPUTS_MODULE}" \
              --arg version "${NEXT_VERSION}" \
              --arg tag "${NEXT_TAG}" \
              --argjson modules "$(cat modules.json)" \
              "${JQ_SCRIPT}" *.support.json
          )
          code=$?; [[ "$code" != "0" ]] && exit $code
          cat | tee modules.json<< EOF
          $_modules
          EOF
      - name: git-commit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPOSITORY: ${{ github.repository }}
        run: |
          git config --global user.email "<>"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GH_REPOSITORY}
          git add modules.json
          git commit -m "chore: Update supported cellophane versions for ${INPUTS_MODULE} ${NEXT_VERSION}"
          git push
