---
name: Run pytest

permissions:
  checks: write
  pull-requests: write

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      publish-results:
        description: 'Publish test results'
        type: boolean
        default: false
      generate-support-json:
        description: 'Generate support json'
        type: boolean
        default: false
      pr-head-sha:
        description: The head sha of the pull request
        type: string
        required: true
      module:
        description: The module to test
        type: string
        required: true
      path:
        description: The working directory (must contain pyproject.toml)
        type: string
        required: true
      version:
        description: The version of the module to test
        type: string
        required: true
      cellophane-repo:
        description: The repository of cellophane to use
        type: string
        required: true
      cellophane-tag:
        description: The version of cellophane to use
        type: string
        required: true
      ignore-fail:
        description: Ignore test failures (when generating support JSON)
        type: boolean
        required: false
        default: false
      check-fail:
        description: Report test failures as a check fail
        type: boolean
        required: false
        default: false

env:
  INPUTS_MODULE: ${{ inputs.module }}
  INPUTS_VERSION: ${{ inputs.version }}
  INPUTS_CELLAPHANE_REPO: ${{ inputs.cellophane-repo }}
  INPUTS_CELLAPHANE_TAG: ${{ inputs.cellophane-tag }}
  INPUTS_IGNORE_FAIL: ${{ inputs.ignore-fail }}
  INPUTS_CHECK_FAIL: ${{ inputs.check-fail }}
  SUPPORT_JSON: ${{ inputs.module }}-${{ inputs.cellophane-tag }}.support.json
  PYTEST_JUNIT_XML: ${{ inputs.module }}-${{ inputs.cellophane-tag }}.pytest.xml

jobs:
  pytest:
    name: Run pytest (${{ inputs.cellophane-tag }})
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.pytest.outputs.result }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: ${{ inputs.pr-head-sha }}
        persist-credentials: false
    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
    - name: install-project
      run: uv sync --frozen --all-extras --dev
    - name: install-cellophane
      run: uv pip install git+https://github.com/${INPUTS_CELLAPHANE_REPO}.git@${INPUTS_CELLAPHANE_TAG} --force-reinstall
    - name: pytest
      id: pytest
      timeout-minutes: 1
      env:
        FORCE_COLOR: false
        COLUMNS: 500
      working-directory: ${{ inputs.path }}
      run: |
        set +e
        uv run --package cellophane-${INPUTS_MODULE} --no-sync pytest --junit-xml=${PYTEST_JUNIT_XML} --tb=short
        code=$?
        if [[ "$code" == "0" ]]; then
          echo ::notice::Tests passed for ${INPUTS_MODULE} ${INPUTS_VERSION} with cellophane ${INPUTS_CELLAPHANE_TAG}
          echo "\"${INPUTS_CELLAPHANE_TAG}\"" > ${SUPPORT_JSON}
          echo result=success | tee -a "$GITHUB_OUTPUT"
        elif [[ "${INPUTS_IGNORE_FAIL}" == "true" ]]; then
          echo ::notice::Ignoring test failures
          echo "\"${INPUTS_CELLAPHANE_TAG}\"" > ${SUPPORT_JSON}
          echo result=failure | tee -a "$GITHUB_OUTPUT"
        elif [[ "$code" == "1" ]]; then
          echo ::warning::Tests failed for ${INPUTS_MODULE} ${INPUTS_VERSION} with cellophane ${INPUTS_CELLAPHANE_TAG}
          echo result=failure | tee -a "$GITHUB_OUTPUT"
        elif [[ "$code" == "5" ]]; then
          echo ::warning::No tests found for ${INPUTS_MODULE}
          echo result=failure | tee -a "$GITHUB_OUTPUT"
        else
          echo ::error::Unexpected pytest exit code $code
          echo result=failure | tee -a "$GITHUB_OUTPUT"
        fi

        if [[ "${INPUTS_CHECK_FAIL}" == "true" ]]; then
          exit $code
        else
          exit 0
        fi

    - uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
      if: (!cancelled() && inputs.publish-results)
      with:
        check_name: Test Results (cellophane@${{ inputs.cellophane-tag }})
        files: ${{ inputs.path }}/${{ env.PYTEST_JUNIT_XML }}
        commit: ${{ inputs.pr-head-sha }}

    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: (!cancelled() && (steps.pytest.outputs.result != 'failure'  || inputs.ignore-fail))
      with:
        name: ${{ env.SUPPORT_JSON }}
        path: ${{ inputs.path }}/${{ env.SUPPORT_JSON }}
        retention-days: 1

    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: (!cancelled())
      with:
        name: ${{ env.PYTEST_JUNIT_XML }}
        path: ${{ inputs.path }}/${{ env.PYTEST_JUNIT_XML }}
        retention-days: 1
