# Move non-release PRs to dev branch
---
name: PR Opened/Edit/Reopened on Dev

permissions: read-all

on: # yamllint disable-line rule:truthy
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
    branches: [dev, main]


concurrency:
  group: ${{ github.event.pull_request.number }}-${{ github.workflow }}

jobs:
  reviewdog-lint:
    name: Lint code
    uses: ./.github/workflows/def_reviewdog-lint.yml
    permissions:
      contents: write
      issues: write
      pull-requests: write
      statuses: write
    concurrency:
      group: ${{ github.ref }}-${{ github.workflow }}-reviewdog-lint
    with:
      head: ${{ github.event.pull_request.head.sha }}
