---
name: Push to main

permissions:
  contents: read

on: # yamllint disable-line rule:truthy
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}

jobs:
  cellophane-releases:
    name: List releases
    runs-on: ubuntu-latest
    outputs:
      releases: ${{ steps.get-tags.outputs.releases }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: -1
        persist-credentials: false
    - name: get-tags
      id: get-tags
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ClinicalGenomicsGBG/cellophane
      run: |
        releases=$(gh release list -L 5 --json tagName --jq '[.[].[]]')
        code=$? [[ "$code" != "0" ]] && exit $code
        echo releases=$releases | tee -a "$GITHUB_OUTPUT"

  modules:
    name: Modules
    uses: ./.github/workflows/def_list-modules.yml
    with:
      has-changes-override-pattern: modules.json

  module-pr:
    name: Create or update release PR
    uses: ./.github/workflows/def_module-pr.yml
    needs: [modules, cellophane-releases]
    permissions:
      contents: write
      pull-requests: write
      checks: write
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.modules.outputs.modules) }}
    with:
      module: ${{ matrix.name }}
      path: ${{ matrix.path }}
      has-changes: ${{ matrix.has-changes }}
      base: main
      head: ${{ github.event.ref }}
      cellophane-repo: ClinicalGenomicsGBG/cellophane
      cellophane-releases: ${{ needs.cellophane-releases.outputs.releases }}

  cleanup:
    name: Cleanup artifacts
    needs: module-pr
    if: always()
    runs-on: ubuntu-latest
    steps:
    - uses: geekyeggo/delete-artifact@176a747ab7e287e3ff4787bf8a148716375ca118 # v6.0.0
      with:
        name: "*"
